/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FamilyTracesRouteImport } from './routes/family-traces'
import { Route as LetterRouteImport } from './routes/letter'
import { Route as RepeatedWordsRouteImport } from './routes/repeated-words'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as TimeCapsuleRouteImport } from './routes/time-capsule'
import { Route as TrajectoryRouteImport } from './routes/trajectory'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyTracesRoute = FamilyTracesRouteImport.update({
  id: '/family-traces',
  path: '/family-traces',
  getParentRoute: () => rootRouteImport,
} as any)
const LetterRoute = LetterRouteImport.update({
  id: '/letter',
  path: '/letter',
  getParentRoute: () => rootRouteImport,
} as any)
const RepeatedWordsRoute = RepeatedWordsRouteImport.update({
  id: '/repeated-words',
  path: '/repeated-words',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeCapsuleRoute = TimeCapsuleRouteImport.update({
  id: '/time-capsule',
  path: '/time-capsule',
  getParentRoute: () => rootRouteImport,
} as any)
const TrajectoryRoute = TrajectoryRouteImport.update({
  id: '/trajectory',
  path: '/trajectory',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/family-traces': typeof FamilyTracesRoute
  '/letter': typeof LetterRoute
  '/repeated-words': typeof RepeatedWordsRoute
  '/stories': typeof StoriesRoute
  '/time-capsule': typeof TimeCapsuleRoute
  '/trajectory': typeof TrajectoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/family-traces': typeof FamilyTracesRoute
  '/letter': typeof LetterRoute
  '/repeated-words': typeof RepeatedWordsRoute
  '/stories': typeof StoriesRoute
  '/time-capsule': typeof TimeCapsuleRoute
  '/trajectory': typeof TrajectoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/family-traces': typeof FamilyTracesRoute
  '/letter': typeof LetterRoute
  '/repeated-words': typeof RepeatedWordsRoute
  '/stories': typeof StoriesRoute
  '/time-capsule': typeof TimeCapsuleRoute
  '/trajectory': typeof TrajectoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/family-traces'
    | '/letter'
    | '/repeated-words'
    | '/stories'
    | '/time-capsule'
    | '/trajectory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/family-traces'
    | '/letter'
    | '/repeated-words'
    | '/stories'
    | '/time-capsule'
    | '/trajectory'
  id:
    | '__root__'
    | '/'
    | '/family-traces'
    | '/letter'
    | '/repeated-words'
    | '/stories'
    | '/time-capsule'
    | '/trajectory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FamilyTracesRoute: typeof FamilyTracesRoute
  LetterRoute: typeof LetterRoute
  RepeatedWordsRoute: typeof RepeatedWordsRoute
  StoriesRoute: typeof StoriesRoute
  TimeCapsuleRoute: typeof TimeCapsuleRoute
  TrajectoryRoute: typeof TrajectoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-traces': {
      id: '/family-traces'
      path: '/family-traces'
      fullPath: '/family-traces'
      preLoaderRoute: typeof FamilyTracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letter': {
      id: '/letter'
      path: '/letter'
      fullPath: '/letter'
      preLoaderRoute: typeof LetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repeated-words': {
      id: '/repeated-words'
      path: '/repeated-words'
      fullPath: '/repeated-words'
      preLoaderRoute: typeof RepeatedWordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-capsule': {
      id: '/time-capsule'
      path: '/time-capsule'
      fullPath: '/time-capsule'
      preLoaderRoute: typeof TimeCapsuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trajectory': {
      id: '/trajectory'
      path: '/trajectory'
      fullPath: '/trajectory'
      preLoaderRoute: typeof TrajectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FamilyTracesRoute: FamilyTracesRoute,
  LetterRoute: LetterRoute,
  RepeatedWordsRoute: RepeatedWordsRoute,
  StoriesRoute: StoriesRoute,
  TimeCapsuleRoute: TimeCapsuleRoute,
  TrajectoryRoute: TrajectoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
